/* Generated by tools/build-offline.cjs; regenerate after runtime changes. */
self.BB_OFFLINE = {
  "version": "760613ffbeac62c2",
  "bytes": 3218364,
  "assets": [
    "./index.html",
    "./burrow-brawl.html",
    "./install.js",
    "./install.css",
    "./manifest.webmanifest",
    "./vendor/engine.js",
    "./vendor/peerjs.min.js",
    "./vendor/fonts.css",
    "./vendor/LICENSE.three.txt",
    "./vendor/LICENSE.peerjs.txt",
    "./vendor/LICENSE.bungee.txt",
    "./vendor/LICENSE.barlow-semi-condensed.txt",
    "./assets/art-data.js",
    "./assets/app/icon-192.png",
    "./assets/app/icon-512.png",
    "./assets/app/icon-maskable-512.png",
    "./assets/app/apple-touch-icon.png",
    "./assets/app/favicon-32.png"
  ]
};
