/* Run npm install in this folder, then npm run build. The checked-in output needs no build. */
const fs = require('node:fs');
const path = require('node:path');
const { createHash } = require('node:crypto');
const { createRequire } = require('node:module');
const root = path.resolve(__dirname, '..');
const dependencies = process.env.BB_BUILD_MODULES;
const req = dependencies ? createRequire(path.resolve(dependencies, '..', 'package.json')) : require;
const pkgRoot = name => path.dirname(req.resolve(name + '/package.json'));
const copy = (from, to) => fs.copyFileSync(from, path.join(root, 'vendor', to));
async function build() {
  if (!process.argv.includes('--cache-only')) {
    await req('esbuild').build({
      stdin: { contents: `import * as THREE from 'three'; export { THREE };
        export { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
        export { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
        export { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
        export { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
        export { ShaderPass } from 'three/addons/postprocessing/ShaderPass.js';`, resolveDir: __dirname },
      nodePaths: dependencies ? [dependencies] : [], bundle: true, minify: true, format: 'iife',
      globalName: 'BB_ENGINE', target: ['es2020'], legalComments: 'inline',
      outfile: path.join(root, 'vendor/engine.js'),
    });
    const threeRoot = path.resolve(path.dirname(req.resolve('three')), '..');
    copy(path.join(threeRoot, 'LICENSE'), 'LICENSE.three.txt');
    copy(path.join(pkgRoot('peerjs'), 'dist/peerjs.min.js'), 'peerjs.min.js');
    copy(path.join(pkgRoot('peerjs'), 'LICENSE'), 'LICENSE.peerjs.txt');
    let css = '/* Locally bundled OFL fonts. Data URLs also support direct-file launch. */\n';
    for (const [font, family, weights] of [['bungee', 'Bungee', [400]], ['barlow-semi-condensed', 'Barlow Semi Condensed', [400, 500, 600, 700, 800]]]) {
      const base = pkgRoot('@fontsource/' + font);
      copy(path.join(base, 'LICENSE'), 'LICENSE.' + font + '.txt');
      for (const weight of weights) for (const subset of ['latin-ext', 'latin']) {
        const bytes = fs.readFileSync(path.join(base, 'files', `${font}-${subset}-${weight}-normal.woff2`));
        const range = subset === 'latin' ? 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD' : 'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0300-0303,U+0305-0307,U+0309-0328,U+032A-036F,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF';
        css += `@font-face{font-family:'${family}';font-style:normal;font-weight:${weight};font-display:swap;src:url(data:font/woff2;base64,${bytes.toString('base64')}) format('woff2');unicode-range:${range}}\n`;
      }
    }
    fs.writeFileSync(path.join(root, 'vendor/fonts.css'), css);
  }
  const files = ['index.html', 'burrow-brawl.html', 'install.js', 'install.css', 'manifest.webmanifest',
    'game.js', 'features-ballistics.js', 'features-surfaces.js', 'assets/surface-data.js',
    'vendor/engine.js', 'vendor/peerjs.min.js', 'vendor/fonts.css', 'vendor/LICENSE.three.txt', 'vendor/LICENSE.peerjs.txt',
    'vendor/LICENSE.bungee.txt', 'vendor/LICENSE.barlow-semi-condensed.txt', 'assets/art-data.js',
    'assets/app/icon-192.png', 'assets/app/icon-512.png', 'assets/app/icon-maskable-512.png',
    'assets/app/apple-touch-icon.png', 'assets/app/favicon-32.png'];
  const hash = createHash('sha256'); let bytes = 0;
  for (const file of [...files, 'sw.js']) { const data = fs.readFileSync(path.join(root, file)); hash.update(file).update(data); bytes += data.length; }
  const manifest = { version: hash.digest('hex').slice(0, 16), bytes, assets: files.map(file => './' + file.split('/').map(encodeURIComponent).join('/')) };
  fs.writeFileSync(path.join(root, 'offline-assets.js'), '/* Generated by tools/build-offline.cjs; regenerate after runtime changes. */\nself.BB_OFFLINE = ' + JSON.stringify(manifest, null, 2) + ';\n');
  console.log(`Offline bundle ${manifest.version}: ${files.length} files, ${(bytes / 1048576).toFixed(2)} MiB`);
}
build().catch(error => { console.error(error); process.exitCode = 1; });
